spring.application.name=workflow-orchestrator
# sqlite
# spring.datasource.url=jdbc:sqlite:workflow.db?busy_timeout=5000
# spring.datasource.driver-class-name=org.sqlite.JDBC

# spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# spring.jpa.hibernate.ddl-auto=update

# spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_orchestrator

spring.datasource.username=postgres

spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect